version: 2

project_name: gw-dash

builds:
  - id: gw-dash
    main: ./main.go
    binary: gw-dash
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "gw-dash_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
